from pathlib import Path
import subprocess
import sys

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')
here = Path(__file__).resolve().parent
r6 = here / 'apply_final_tci_omnirig_r6_overlay.py'
if not r6.exists():
    raise SystemExit('[FAIL] R6 overlay missing')

# R7 is incremental over R6. R6 proved that device-name gating was not the
# complete cause of the RX-QSY failure. The native JTDX 2.2.159 do_frequency()
# waits on tci_loop1_, but tci_done1 is shared by several unrelated TCI events.
# One such event can therefore wake mysleep1(2000) before the requested VFO0
# acknowledgement arrives, after which JTDX immediately reports
# "TCI failed set rxfreq". R7 keeps the native state machine but makes the wait
# target-specific: unrelated tci_done1 wakeups no longer complete RX QSY.
subprocess.run([sys.executable, str(r6), str(root)], check=True)

pp = root / 'patch_superhound.py'
bp = root / 'BUILD_JTDX_SUPERHOUND_MSI.ps1'
if not pp.exists() or not bp.exists():
    raise SystemExit('[FAIL] FINAL-TCI patcher/builder missing after R6 overlay')

s = pp.read_text(encoding='utf-8')
marker = '# SQ4KOU R7: RX QSY acknowledgement wait is target-specific, not signal-specific.'
if marker not in s:
    block = r"""

# SQ4KOU R7: RX QSY acknowledgement wait is target-specific, not signal-specific.
# tci_done1 is shared by VFO, mode, ready/start/audio and other TCI paths. The
# original single mysleep1(2000) can therefore be released by an unrelated TCI
# event and test rx_frequency_ too early. Patch only the RX do_frequency wait
# immediately preceding the real "TCI failed set rxfreq" path; do not touch
# other sleeps/state-machine paths.
p, t = load('TCITransceiver.cpp')

if '#include <QElapsedTimer>' not in t:
    inc_old = '#include <QThread>\n'
    inc_new = '#include <QThread>\n#include <QElapsedTimer>\n'
    if t.count(inc_old) != 1:
        raise SystemExit(f'[FAIL] R7 QElapsedTimer include anchor count={t.count(inc_old)}')
    t = t.replace(inc_old, inc_new, 1)

if 'QElapsedTimer rx_ack_wait;' not in t:
    err_marker = 'error_ = tr ("TCI failed set rxfreq");'
    err_pos = t.find(err_marker)
    if err_pos < 0:
        raise SystemExit('[FAIL] R7 RX failure marker missing')

    func_pos = t.rfind('TCITransceiver::do_frequency', 0, err_pos)
    if func_pos < 0:
        raise SystemExit('[FAIL] R7 do_frequency function marker missing')

    sleep_pos = t.rfind('mysleep1(2000);', func_pos, err_pos)
    if sleep_pos < 0:
        raise SystemExit('[FAIL] R7 RX-QSY mysleep1(2000) missing before rxfreq failure')

    send_pos = t.rfind('sendTextMessage(cmd);', func_pos, sleep_pos)
    if send_pos < 0:
        raise SystemExit('[FAIL] R7 RX-QSY sendTextMessage(cmd) missing before wait')

    # Guard against accidentally selecting a distant/unrelated sleep.
    if sleep_pos - send_pos > 700:
        raise SystemExit(f'[FAIL] R7 RX-QSY send/wait distance too large: {sleep_pos-send_pos}')

    replacement = '''// SQ4KOU R7: wait for the requested RX VFO value, not for an arbitrary\n          // tci_done1 wakeup generated by another TCI message.\n          QElapsedTimer rx_ack_wait;\n          rx_ack_wait.start();\n          while (requested_rx_frequency_ != rx_frequency_ && inConnected &&\n                 rx_ack_wait.elapsed() < 2000) {\n            int const left = 2000 - static_cast<int>(rx_ack_wait.elapsed());\n            if (left <= 0) break;\n            mysleep1(left > 250 ? 250 : left);\n          }\n\n          // If the command/echo was genuinely lost, resend once. A final\n          // mismatch is still reported by the native failure path below.\n          if (requested_rx_frequency_ != rx_frequency_ && inConnected) {\n            sendTextMessage(cmd);\n            rx_ack_wait.restart();\n            while (requested_rx_frequency_ != rx_frequency_ && inConnected &&\n                   rx_ack_wait.elapsed() < 1000) {\n              int const left = 1000 - static_cast<int>(rx_ack_wait.elapsed());\n              if (left <= 0) break;\n              mysleep1(left > 250 ? 250 : left);\n            }\n          }'''
    t = t[:sleep_pos] + replacement + t[sleep_pos + len('mysleep1(2000);'):]
    print(f'[OK] R7 patched target RX wait at offset {sleep_pos}')
else:
    print('[SKIP] R7 target-specific RX wait already present')

save(p, t)

_, t = load('TCITransceiver.cpp')
for needle in [
    '#include <QElapsedTimer>',
    'QElapsedTimer rx_ack_wait;',
    'rx_ack_wait.elapsed() < 2000',
    'rx_ack_wait.restart();',
    'rx_ack_wait.elapsed() < 1000',
    'requested_rx_frequency_ != rx_frequency_ && inConnected',
    'error_ = tr ("TCI failed set rxfreq");',
]:
    if needle not in t:
        raise SystemExit(f'[FAIL] R7 target-specific RX-QSY postcheck missing {needle!r}')
print('[PASS] R7 target-specific RX-QSY acknowledgement wait + bounded resend')
"""
    s += block
    pp.write_text(s, encoding='utf-8', newline='\n')

b = bp.read_text(encoding='utf-8')
if "MSI_VERSION='2.2.204'" not in b:
    if b.count("MSI_VERSION='2.2.203'") != 1:
        raise SystemExit('[FAIL] R7 MSI version 2.2.203 anchor missing')
    b = b.replace("MSI_VERSION='2.2.203'", "MSI_VERSION='2.2.204'", 1)

old_name = "MSI_NAME='JTDX-SuperHound-2.2.159-FINAL-TCI-NATIVE-OMNIRIG-R6-VFO0ACK-win64'"
new_name = "MSI_NAME='JTDX-SuperHound-2.2.159-FINAL-TCI-NATIVE-OMNIRIG-R7-RXACK-win64'"
if new_name not in b:
    if b.count(old_name) != 1:
        raise SystemExit('[FAIL] R7 MSI name anchor missing')
    b = b.replace(old_name, new_name, 1)

bp.write_text(b, encoding='utf-8', newline='\n')

for needle in [
    marker,
    '-DJTDX_ENABLE_OMNIRIG=ON',
    "MSI_VERSION='2.2.204'",
    new_name,
]:
    haystack = pp.read_text(encoding='utf-8') if needle == marker else bp.read_text(encoding='utf-8')
    if needle not in haystack:
        raise SystemExit(f'[FAIL] R7 overlay postcheck missing {needle!r}')

print('[PASS] R7 = R6 + target-specific RX VFO acknowledgement wait; OmniRig preserved')
